sonar.projectKey=himanshugohil18_DevOps-github-actions-kubernetes-masterclass
sonar.organization=himanshugohil18

sonar.projectName=DevOps-github-actions-kubernetes-masterclass

sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/*.min.js,**/vendor/**

sonar.sourceEncoding=UTF-8
